language: python

cache:
  - pip: true
  - directories:
      - $HOME/Library/Caches/pypoetry
      - $HOME/.cache/pypoetry

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3

matrix:
  include:
    - name: "Python: 3.6"
      os: osx
      language: shell
      python: 3.6
    - name: "Python: 3.7"
      os: osx
      language: shell
      python: 3.7
    - name: "Python: 3.8"
      os: osx
      language: shell
      python: 3.8
    - name: "Python: 3.9"
      os: osx
      language: shell
      python: 3.9
    - name: "Python: pypy3"
      os: osx
      language: shell
      python: pypy3

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+/

install:
  - make install

script:
  - make test

after_success:
  - poetry run codecov

before_deploy:
  - poetry config repositories.testpypi https://test.pypi.org/legacy/
  - poetry config http-basic.testpypi $TEST_PYPI_USER $TEST_PYPI_PASS
  - poetry build

deploy:
  provider: script
  script: poetry publish -r testpypi
  skip_cleanup: true
  on:
    branch: develop
    condition: $TRAVIS_PYTHON_VERSION = "3.6" && $TRAVIS_OS_NAME == "linux"